---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: pod-running-policy
  labels:
    name: podsecuritypolicy
spec:
  privileged: true
  allowedCapabilities:
    - IPC_LOCK
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
  - '*'
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-security-policy-role
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs: ["use"]
  resourceNames:
    - pod-running-policy
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: use-pod-security-policy
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: pod-security-policy-role
  apiGroup: rbac.authorization.k8s.io
